# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

# Les pages Gitlab supportent la compression avec gzip
# OK : find public -type f -print0 -exec gzip -k -9 {} \;
# L'option -r (recursif) de gzip n'est pas acceptée
# → contournement avec la commande unix 'find' qui liste les fichiers recursivement 
# KO : find public -type f -print0 -exec gzip -9 {}
# KO : find public -type f -print0 | xargs -0r gzip -9 → rien sur le site (manque option -k ?)
# Note : il faut ajouter \; pour marquer la fin de la commande exec
pages:
  script:
  - hugo --minify 
  - find public -type f -print0 -exec gzip -k -9 {} \;
  artifacts:
    paths:
    - public
  only:
  - master
